CREATE TABLE dominio_status_orcamento (
    codigo varchar(30) PRIMARY KEY,
    descricao varchar(255) NOT NULL
);

CREATE TABLE dominio_tipo_item_orcamento (
    codigo varchar(20) PRIMARY KEY,
    descricao varchar(255) NOT NULL
);

CREATE TABLE dominio_metodo_pagamento (
    codigo varchar(30) PRIMARY KEY,
    descricao varchar(255) NOT NULL
);

CREATE TABLE dominio_status_pagamento (
    codigo varchar(30) PRIMARY KEY,
    descricao varchar(255) NOT NULL
);

CREATE TABLE orcamento (
    id uuid PRIMARY KEY,
    ordem_de_servico_id uuid NOT NULL,
    valor_total numeric(14, 2) NOT NULL,
    status varchar(30) NOT NULL,
    criado_em timestamptz NOT NULL,
    atualizado_em timestamptz NOT NULL,
    CONSTRAINT fk_orcamento_status
        FOREIGN KEY (status)
        REFERENCES dominio_status_orcamento (codigo),
    CONSTRAINT ck_orcamento_valor_total_nao_negativo CHECK (valor_total >= 0)
);

CREATE TABLE orcamento_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orcamento_id uuid NOT NULL,
    tipo varchar(20) NOT NULL,
    item_id uuid NOT NULL,
    referencia_catalogo_id uuid,
    nome varchar(255) NOT NULL,
    quantidade numeric(15, 3) NOT NULL,
    valor_unitario numeric(14, 2) NOT NULL,
    valor_total numeric(14, 2) NOT NULL,
    CONSTRAINT fk_orcamento_item_orcamento
        FOREIGN KEY (orcamento_id)
        REFERENCES orcamento (id),
    CONSTRAINT fk_orcamento_item_tipo
        FOREIGN KEY (tipo)
        REFERENCES dominio_tipo_item_orcamento (codigo),
    CONSTRAINT ck_orcamento_item_quantidade_positiva CHECK (quantidade > 0),
    CONSTRAINT ck_orcamento_item_valor_unitario_nao_negativo CHECK (valor_unitario >= 0),
    CONSTRAINT ck_orcamento_item_valor_total_nao_negativo CHECK (valor_total >= 0)
);

CREATE TABLE pagamento (
    id uuid PRIMARY KEY,
    ordem_de_servico_id uuid NOT NULL,
    orcamento_id uuid NOT NULL,
    valor numeric(14, 2) NOT NULL,
    metodo varchar(30) NOT NULL,
    status varchar(30) NOT NULL,
    provedor varchar(100),
    transacao_externa_id varchar(255),
    motivo_recusa varchar(500),
    criado_em timestamptz NOT NULL,
    atualizado_em timestamptz NOT NULL,
    CONSTRAINT fk_pagamento_orcamento
        FOREIGN KEY (orcamento_id)
        REFERENCES orcamento (id),
    CONSTRAINT fk_pagamento_metodo
        FOREIGN KEY (metodo)
        REFERENCES dominio_metodo_pagamento (codigo),
    CONSTRAINT fk_pagamento_status
        FOREIGN KEY (status)
        REFERENCES dominio_status_pagamento (codigo),
    CONSTRAINT uk_pagamento_orcamento UNIQUE (orcamento_id),
    CONSTRAINT ck_pagamento_valor_nao_negativo CHECK (valor >= 0)
);

CREATE TABLE outbox_event (
    id uuid PRIMARY KEY,
    aggregate_id varchar(100) NOT NULL,
    event_type varchar(100) NOT NULL,
    event_version integer NOT NULL,
    topic varchar(200) NOT NULL,
    producer varchar(100) NOT NULL,
    payload jsonb NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'PENDING',
    correlation_id varchar(100),
    occurred_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    published_at timestamptz,
    attempts integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz,
    last_error text,
    CONSTRAINT ck_outbox_event_status CHECK (status IN ('PENDING', 'PUBLISHED', 'FAILED'))
);

CREATE INDEX ix_orcamento_ordem_servico ON orcamento (ordem_de_servico_id);
CREATE INDEX ix_orcamento_status ON orcamento (status, atualizado_em);
CREATE INDEX ix_orcamento_item_orcamento ON orcamento_item (orcamento_id);
CREATE INDEX ix_orcamento_item_item ON orcamento_item (item_id);
CREATE INDEX ix_pagamento_ordem_servico ON pagamento (ordem_de_servico_id);
CREATE INDEX ix_pagamento_orcamento ON pagamento (orcamento_id);
CREATE INDEX ix_pagamento_status ON pagamento (status, atualizado_em);
CREATE INDEX ix_outbox_event_status_next_attempt ON outbox_event (status, next_attempt_at, created_at);
CREATE INDEX ix_outbox_event_aggregate ON outbox_event (aggregate_id, occurred_at);
